const guides={
bill:{title:"A bill is due or already late",first:"Open the bill and find the company name, amount, due date, and phone number.",words:"Hi, I’m calling because I may not be able to pay the full amount by the due date. What payment arrangements or hardship options are available?",steps:["Write down the exact amount and due date.","Check your available money without guessing.","Contact the company before sending a partial payment.","Write down the representative’s name and what was agreed.","Set a reminder for the new payment date."],help:"shutoff, eviction, repossession, court, or collections are mentioned—or you do not understand the agreement."},
appointment:{title:"You need to make an appointment",first:"Write one sentence explaining what you need before you call.",words:"Hi, my name is ____. I need to schedule an appointment for ____. I’m available ____. What information do you need from me?",steps:["Find the correct phone number or online scheduling page.","Have your calendar, ID, and insurance card nearby if relevant.","Use the script and ask them to repeat anything unclear.","Save the date, time, address, and arrival instructions.","Set two reminders and note anything you must bring."],help:"the issue is urgent, symptoms are severe, you feel unsafe, or you cannot understand the instructions."},
work:{title:"There is a job or schedule problem",first:"Contact the person who actually controls the schedule as soon as you know there is a problem.",words:"Hi ____. I need to let you know that ____. I can ____. What do you need me to do next?",steps:["Check the written schedule or policy before assuming.","Separate the facts from what you fear might happen.","Call or message the correct manager promptly.","Offer one realistic solution without promising what you cannot do.","Save the message or write down the conversation."],help:"you are being threatened, harassed, denied earned pay, asked to do something unsafe, or pressured to lie."},
paperwork:{title:"You do not understand a form",first:"Do not sign yet. Find the title of the form and who gave it to you.",words:"I want to make sure I understand this before I sign it. Can you explain what this section means and give me time to review it?",steps:["Read the title and the instructions at the top.","Circle words or questions you do not understand.","Gather only the documents the instructions specifically request.","Ask the organization—not a random online commenter—for clarification.","Photograph or copy the completed form before submitting it."],help:"the form affects housing, court, debt, benefits, immigration, employment rights, or asks for sensitive information unexpectedly."},
mistake:{title:"You made a mistake",first:"Stop hiding from it long enough to name exactly what happened—without calling yourself names.",words:"I made a mistake with ____. Here is what happened. I’m working on ____. What is the best next step to fix this?",steps:["Write the facts in two or three sentences.","Check whether anyone is unsafe or a deadline is passing.","Tell the right person before the problem grows.","Ask what repair or correction is actually needed.","Do the next repair step and keep proof that you did it."],help:"someone could be hurt, money or legal rights are involved, or another person is pressuring you to hide what happened."},
conflict:{title:"You need to handle a hard conversation",first:"Decide the one thing you need the other person to understand or do.",words:"I want to talk about ____. When ____ happened, it affected me by ____. What I need now is ____. Can we talk about that?",steps:["Wait until you can speak without yelling or threatening.","Choose a private but safe place and a reasonable time.","Describe one specific event instead of every past problem.","State one clear request or boundary.","End the conversation if it becomes unsafe or cruel."],help:"there are threats, stalking, violence, coercion, fear of retaliation, or you cannot safely say no."},
overwhelm:{title:"Everything feels like too much",first:"Choose the closest real deadline—not the loudest worry in your head.",words:"I’m overwhelmed and need help choosing the first step. The things due soon are ____. Can you help me sort what must happen today?",steps:["Drink water and take five slow breaths.","Write every worry down without organizing it.","Mark anything involving safety, today’s deadline, food, shelter, or medicine.","Choose one task that takes under ten minutes.","After that task, pause before choosing another."],help:"you cannot stay safe, cannot care for basic needs, feel hopeless, or are thinking about hurting yourself or someone else."}
};
const buttons=[...document.querySelectorAll("[data-topic]")],plan=document.querySelector("#plan"),list=document.querySelector("#checklist");let active=localStorage.getItem("almostAdultTopic")||"";
function saved(k){try{return JSON.parse(localStorage.getItem(`almostAdult-${k}`))||[]}catch{return[]}}
function progress(){const boxes=[...list.querySelectorAll("input")],done=boxes.filter(x=>x.checked).length;document.querySelector("#progressText").textContent=`${done} of ${boxes.length} complete`;document.querySelector("#progressBar").style.width=`${boxes.length?done/boxes.length*100:0}%`;localStorage.setItem(`almostAdult-${active}`,JSON.stringify(boxes.map(x=>x.checked)))}
function show(k,scroll=true){const g=guides[k];if(!g)return;active=k;localStorage.setItem("almostAdultTopic",k);buttons.forEach(b=>b.classList.toggle("selected",b.dataset.topic===k));document.querySelector("#planTitle").textContent=g.title;document.querySelector("#firstMove").textContent=g.first;document.querySelector("#words").textContent=g.words;document.querySelector("#helpWhen").textContent=g.help;const was=saved(k);list.replaceChildren(...g.steps.map((s,i)=>{const li=document.createElement("li"),label=document.createElement("label"),box=document.createElement("input"),text=document.createElement("span");box.type="checkbox";box.checked=Boolean(was[i]);box.setAttribute("aria-label",`Complete step ${i+1}`);box.addEventListener("change",progress);text.textContent=s;label.append(box,text);li.append(label);return li}));plan.hidden=false;progress();if(scroll)plan.scrollIntoView({behavior:"smooth",block:"start"})}
buttons.forEach(b=>b.addEventListener("click",()=>show(b.dataset.topic)));
document.querySelector("#copyWords").addEventListener("click",async()=>{const b=document.querySelector("#copyWords");try{await navigator.clipboard.writeText(document.querySelector("#words").textContent);b.textContent="Copied";setTimeout(()=>b.textContent="Copy these words",1500)}catch{b.textContent="Press and hold the words to copy"}});
document.querySelector("#resetAll").addEventListener("click",()=>{Object.keys(guides).forEach(k=>localStorage.removeItem(`almostAdult-${k}`));localStorage.removeItem("almostAdultTopic");active="";buttons.forEach(b=>b.classList.remove("selected"));plan.hidden=true});
let left=60,timer=null;const display=document.querySelector("#countdown"),timerButton=document.querySelector("#oneMinute");function draw(){display.textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,"0")}`};timerButton.addEventListener("click",()=>{if(timer){clearInterval(timer);timer=null;timerButton.textContent="Continue reset";return}if(left===0)left=60;timerButton.textContent="Pause";timer=setInterval(()=>{left--;draw();if(left<=0){clearInterval(timer);timer=null;timerButton.textContent="Reset complete"}},1000)});if(active)show(active,false);
